import turtle
t = turtle.Turtle()
t.speed(5) # 1:slowest, 3:slow, 5:normal, 10:fast, 0:fastest
screen = turtle.Screen() 

t = turtle.Turtle()
t.color("black")

t.penup()
t.goto(-200, -200)
t.pendown()
t.fillcolor("cyan")
t.begin_fill()
for _ in range(2):
    t.forward(400)
    t.left(90)
    t.forward(250)
    t.left(90)
t.end_fill()

t.fillcolor("brown")
t.begin_fill()
t.goto(-200, 50)
t.goto(0, 200)
t.goto(200, 50)
t.goto(-200, 50)
t.end_fill()

t.penup()
t.goto(-50, -200)
t.pendown()
t.fillcolor("red")
t.begin_fill()
for _ in range(2):
    t.forward(100)
    t.left(90)
    t.forward(150)
    t.left(90)
t.end_fill()

t.penup()
t.goto(-150, -50)
t.pendown()
t.fillcolor("white")
t.begin_fill()
for _ in range(2):
    t.forward(75)
    t.left(90)
    t.forward(75)
    t.left(90)
t.end_fill()

t.penup()
t.goto(75, -50)
t.pendown()
t.fillcolor("white")
t.begin_fill()
for _ in range(2):
    t.forward(75)
    t.left(90)
    t.forward(75)
    t.left(90)
t.end_fill()

t.hideturtle()
t = turtle.Turtle()
w = turtle.Screen()
w.bgcolor("black")
t.color("white")
t.begin_fill()
t.circle(80)
t.end_fill()
t.hideturtle()
w.exitonclick()
